### ISSUE TITLE
Facing issue while using git-chglog inside the docker container

### ISSUE THREAD

**Issue by neeraj00890** [git-chglog/git-chglog#161]
Hi have below mentioned command inside a dockerfile
FROM node:12-alpine as tools-image
WORKDIR /home/node/app
RUN chown -R node:node /home/node/app\
    && apk add git
COPY libs/tools/package.json libs/tools/
COPY package.json yarn.lock ./
COPY libs/shared/package.json libs/shared/
COPY libs/core/package.json libs/core/

RUN yarn install --production=false && yarn cache  clean --all

COPY . .
ARG GIT_ACCESS_TOKEN
ARG GIT_USER_NAME
RUN git init\ 
    && git remote add origin https://$GIT_ACCESS_TOKEN:$GIT_USER_NAME@gitlab.com/test/test.git\
    && git fetch origin master
ADD https://github.com/git-chglog/git-chglog/releases/download/v0.14.2/git-chglog_0.14.2_linux_amd64.tar.gz /user/lib/
RUN tar -xf /user/lib/git-chglog_0.14.2_linux_amd64.tar.gz -C /user/lib/
RUN /user/lib/git-chglog --version

On the last line is giving me and exact version without any issue but whien i issue command for my ts file  using execa

const nextChangelogEntry = (
        await execa("/user/lib/git-chglog", ["--next-tag", version, version], {
            cwd: rootPath
        })
    ).stdout;

its giving me below error: 
Checking out to branch release-0.2.0...
Updating changelog...
Error: Command failed with exit code 1: /user/lib/git-chglog --next-tag 0.2.0 0.2.0
 ERROR  exit status 128
    at makeError (/home/node/app/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/node/app/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at updateChangelog (/home/node/app/scripts/release.ts:315:9)
    at release (/home/node/app/scripts/release.ts:173:5)
    at /home/node/app/scripts/release.ts:362:9 {
  shortMessage: 'Command failed with exit code 1: /user/lib/git-chglog --next-tag 0.2.0 0.2.0',
  command: '/user/lib/git-chglog --next-tag 0.2.0 0.2.0',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: ' ERROR  exit status 128',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Task failed!

git-chglog version 0.14.2

**Comment by mavogel** [comment]
Hi @neeraj00890 , we're happy to help. Could you format you snippets, so they are readable and highlighted. Furthermore, please describe the current and expected behaviour. Thank you.
